### PR TITLE
Feature adding simplecov

### PR DESCRIPTION
**Pull request by hgwr**
What you want to achieve with this pull request
---

- I would like to add simplecov gem.

Why
---

- I like to see the coverage rate.
- Yeah, I know that coverage rate is not related to software quality. But I like it. 😄

What
---

- Add some files to .gitignore
  - Specifically I added `*~`. Yes, because I am an Emacs user. 🙋‍♂️

How to confirm this change 
---

```
$ bin/bundle install --path vendor/bundle
$ bin/bundle exec rspec
$ open coverage/index.html
```

Screenshot
---

スクリーンショット 2019-12-14 9 54 00

### CODE REVIEW

**Comment by hgwr** [comment]
@cgeb Chris-さん How are you doing?
I am fine. 😊 Hope you are doing well too. 🙏

**Comment by cgeb** [comment]
@hgwr Hi Hagiwara-san, I'm doing great! Glad that you are doing well too 😃 
We should get a drink sometimes 🍻

**Comment by hgwr** [comment]
@cgeb I am most glad that you are doing great! 😄 
I am working in Shinjuku now. Please invite me out anytime! 
いつでも飲みに行けます。いや、わたしはお酒をやめましたが 😁

**Comment by hgwr** [comment]
Thank you for mergeing my pull request!

**Pull request merged**
